<a href="https://colab.research.google.com/github/Kamil-F/DataSciencePythonAtoZ/blob/main/template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")

Hello


In [1]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
dir(np)

In [ ]:
help(np.array)

1D Array

In [4]:
x = np.array([1, 3])
x

array([1, 3])

In [5]:
print(x)

[1 3]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.ndim

1

In [8]:
x.shape

(2,)

In [9]:
x.size

2

In [10]:
x.dtype

dtype('int64')

In [14]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [15]:
x.dtype

dtype('float64')

2D Array

In [18]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [19]:
x.ndim

2

In [20]:
x.shape

(2, 2)

In [21]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [22]:
x.shape

(2, 3)

3D Array

In [26]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
      
      [[4, 1, 3],
       [4, 2, 1]]]
  )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [27]:
x.ndim

3

In [28]:
x.shape

(2, 2, 3)

In [29]:
#3 elementy, po 2 wiersze, 3 kolumny